### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by myles** [myles/myles.coffee#1]
[57 Little Things to Double Check Before Your Website Launch](http://blog.hubspot.com/marketing/website-launch-checklist)
## Page Content
- [x] Web copywriting has been proofread. Spelling and grammar are correct.
- [x] Paragraphs, headers, lists, and other formatting are correct.
- [x] Copyright date (perhaps in the footer) includes the current year.
- [x] Company contact details are accurate throughout the website.
- [x] Generic content, such as lorem ipsum, has been properly removed and replaced.
- [x] Images are in the correct places, formatted and working on all devices.
- [x] Videos are in the correct places, formatted and working on all devices.
- [x] Audio files are in the correct places, formatted and working on all devices.
- [x] All premium content, such as case studies, ebooks, and whitepapers, have been proofread. Spelling and grammar are correct.
- [x] All premium content, such as case studies, ebooks, and whitepapers, are stored in their proper libraries/databases and work properly.
- [x] Rights to images, fonts, and other content have been properly licensed and/or cited.
## Design
- [ ] Website pages are compatible across browsers (IE 7 8, 9 and 10, Firefox, Chrome, Safari).
- [ ] Website pages are compatible across devices (Android, iPhone, tablets).
- [x] CSS/HTML is properly validated.
- [x] Scripts are optimized across web pages.
- [ ] Images are optimized across web pages.
- [x] CSS is optimized across web pages.
- [x] Favicon is in place and rendering properly.
- [x] Paragraph styles are working properly (headers, lists, block quotes).
## Functionality
- [x] Forms are submitting data properly.
- [x] Thank-you message or page displays after form is submitted.
- [x] Form data is being emailed to a recipient and/or stored in a company database.
- [x] Auto-responders are working properly (if applicable).
- [x] Internal links across web pages are working properly.
- [x] External links across web pages are working properly, and open in a new tab.
- [x] Soci
